# Generated by Django 5.1.1 on 2024-10-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jurados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurado',
            old_name='fk_rol_id',
            new_name='rol',
        ),
    ]
