# Generated by Django 5.1.1 on 2024-10-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jurados', '0002_rename_fk_rol_id_jurado_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspecto', models.CharField(max_length=60)),
                ('indicador', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField()),
                ('criterio', models.TextField()),
            ],
        ),
    ]
