# Generated by Django 5.1.1 on 2024-10-30 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativos', '0007_delete_asignacion'),
        ('Alumnos', '0018_proyecto_cargo'),
        ('Jurados', '0003_rubrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPriEnvio', models.DateField(blank=True, null=True)),
                ('drivePriPdf', models.TextField(blank=True, null=True)),
                ('fechaSegEnvio', models.DateField(blank=True, null=True)),
                ('driveSegPdf', models.TextField(blank=True, null=True)),
                ('fechaTerEnvio', models.DateField(blank=True, null=True)),
                ('driveTerPdf', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField(blank=True, null=True)),
                ('notaFinal', models.IntegerField(blank=True, null=True)),
                ('administrativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administrativos.administrativo')),
                ('jurado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jurados.jurado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.proyecto')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alumnos.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaPriPdf', models.IntegerField(blank=True, null=True)),
                ('notaSegPdf', models.IntegerField(blank=True, null=True)),
                ('notaTerPdf', models.IntegerField(blank=True, null=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jurados.archivo')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jurados.asignacion')),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPriRev', models.DateField(blank=True, null=True)),
                ('calPriPdf', models.IntegerField(blank=True, null=True)),
                ('observacionPriPdf', models.TextField(blank=True, null=True)),
                ('fechaSegRev', models.DateField(blank=True, null=True)),
                ('calSegPdf', models.IntegerField(blank=True, null=True)),
                ('observacionSegPdf', models.TextField(blank=True, null=True)),
                ('fechaTerRev', models.DateField(blank=True, null=True)),
                ('calTerPdf', models.IntegerField(blank=True, null=True)),
                ('observacionTerPdf', models.TextField(blank=True, null=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jurados.archivo')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jurados.asignacion')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jurados.rubrica')),
            ],
        ),
    ]
