# Generated by Django 5.1.1 on 2024-10-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jurados', '0004_archivo_asignacion_reporte_notas_rubrica_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte_notas',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='rubrica_revision',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='reporte_notas',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='rubrica_revision',
            name='rubrica',
        ),
        migrations.RemoveField(
            model_name='rubrica_revision',
            name='asignacion',
        ),
        migrations.RenameField(
            model_name='asignacion',
            old_name='fechaRegistro',
            new_name='fechaAsigancion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='drivePdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='estadoEnvio',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='estadoRevision',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fechaEnvio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fechaRevision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='observacionPdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.DeleteModel(
            name='Reporte_Notas',
        ),
        migrations.DeleteModel(
            name='Rubrica',
        ),
        migrations.DeleteModel(
            name='Rubrica_Revision',
        ),
    ]
