# Generated by Django 5.1.1 on 2024-10-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jurados', '0005_remove_reporte_notas_archivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='fechaAsigancion',
            new_name='fechaAsignacion',
        ),
    ]
