# Generated by Django 5.1.1 on 2024-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jurados', '0006_rename_fechaasigancion_asignacion_fechaasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurado',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
