# Generated by Django 5.1.1 on 2024-10-12 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta_Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFut', models.DateField()),
                ('estadoFut', models.CharField(max_length=50)),
                ('pdfFut', models.FileField(blank=True, null=True, upload_to='pdfs-fut/')),
                ('observacionFut', models.CharField(max_length=150)),
                ('fechaCarta', models.DateField()),
                ('estadoCarta', models.CharField(max_length=50)),
                ('pdfCarta', models.FileField(blank=True, null=True, upload_to='pdfs-carta/')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Proyecto_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=15)),
                ('notaPromocional', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.alumno')),
                ('carta_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.carta_acceso')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='carta_acceso',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.tramite'),
        ),
    ]
