# Generated by Django 5.1.1 on 2024-10-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_carta_acceso_proyecto_tramite_alter_alumno_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_alumno',
            name='carta_acceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.carta_acceso'),
        ),
    ]
