# Generated by Django 5.1.1 on 2024-10-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_alter_proyecto_alumno_carta_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_alumno',
            name='notaPromocional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto_alumno',
            name='semestre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
