# Generated by Django 5.1.1 on 2024-10-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0005_alter_proyecto_alumno_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_alumno',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.proyecto'),
        ),
    ]
