# Generated by Django 5.1.1 on 2024-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0007_alter_carta_acceso_fechacarta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta_acceso',
            name='pdfCarta',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carta_acceso',
            name='pdfFut',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
