# Generated by Django 5.1.1 on 2024-10-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0008_alter_carta_acceso_pdfcarta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta_acceso',
            name='pdfCarta',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='carta_acceso',
            name='pdfFut',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
