# Generated by Django 5.1.1 on 2024-10-29 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0010_alter_carta_acceso_pdfcarta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestreAcademico', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto_alumno',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.semestre'),
        ),
    ]
