# Generated by Django 5.1.1 on 2024-10-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0011_semestre_alter_proyecto_alumno_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='semestreAcademico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
