# Generated by Django 5.1.1 on 2024-10-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0012_alter_semestre_semestreacademico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto_alumno',
            name='semestre',
        ),
        migrations.DeleteModel(
            name='Semestre',
        ),
    ]
