# Generated by Django 5.1.1 on 2024-10-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0015_semestrert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semestrert',
        ),
    ]
