# Generated by Django 5.1.1 on 2024-10-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0016_delete_semestrert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta_acceso',
            name='estadoCarta',
        ),
    ]
