# Generated by Django 5.1.1 on 2024-10-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0017_remove_carta_acceso_estadocarta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
