# Generated by Django 5.1.1 on 2024-11-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0019_alumno_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_alumno',
            name='dictamenPdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
