# Generated by Django 5.1.1 on 2024-11-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0021_alter_proyecto_alumno_dictamenpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto_alumno',
            name='dictamenPdf',
        ),
        migrations.AddField(
            model_name='proyecto_alumno',
            name='resolucionPdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfResolucion/'),
        ),
    ]
