# Generated by Django 5.1.1 on 2024-11-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0022_remove_proyecto_alumno_dictamenpdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_alumno',
            name='dictamenPdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfDictamen/'),
        ),
    ]
