# Generated by Django 5.1.1 on 2024-10-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativos', '0001_initial'),
        ('Alumnos', '0018_proyecto_cargo'),
        ('Jurados', '0002_rename_fk_rol_id_jurado_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField(blank=True, null=True)),
                ('notaFinal', models.IntegerField()),
                ('administrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrativos.administrativo')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jurados.jurado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.proyecto')),
            ],
        ),
    ]
