# Generated by Django 5.1.1 on 2024-10-30 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativos', '0002_asignacion'),
        ('Jurados', '0002_rename_fk_rol_id_jurado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='jurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jurados.jurado'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='notaFinal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
