# Generated by Django 5.1.1 on 2024-10-30 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativos', '0004_alter_asignacion_administrativo'),
        ('Alumnos', '0018_proyecto_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.semestre'),
        ),
    ]
