# Generated by Django 5.1.1 on 2024-10-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativos', '0006_alter_asignacion_administrativo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignacion',
        ),
    ]
