# Generated by Django 5.1.1 on 2024-11-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativos', '0007_delete_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
